"""rename username to fullname in users

Revision ID: 0c8a9730348b
Revises: 1fbe15420054
Create Date: 2026-07-03 15:37:50.073790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c8a9730348b'
down_revision: Union[str, Sequence[str], None] = '1fbe15420054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users','username',new_column_name='fullname', existing_type=sa.String(length=255))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "fullname",
        new_column_name="username",
         existing_type=sa.String(length=255)
    )
    # ### end Alembic commands ###
